Update sv-disable

diff --git a/sv-disable b/sv-disable
--- a/sv-disable
+++ b/sv-disable
@@ -1,20 +1,21 @@
-#!/bin/sh
+#!/usr/bin/env sh
 
 show_help(){
-
-    printf 'Usage:
+    printf -- 'Usage:
     sv-disable <service-name>
 
     Disabling a service will make it not autostart
 '
 }
+
 if [ -z "$1" ];then
     show_help
     exit 1
 fi
-if [ -u "$SVDIR" ];then
-    >&2 echo "Error: SVDIR not set"
+if [ -z "${SVDIR}" ];then
+    1>&2 echo "Error: SVDIR not set"
     exit 1
 fi
-touch "$SVDIR/$1/down"
-sv down $1
+
+: >> "${SVDIR}/${1}/down"
+sv down "$1"
